workflows:
  android-release:
    name: Android Release Build
    working_directory: Engioe
    environment:
      java: "17"
    
    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
