workflows:
  android-release:
    name: Android Release

    environment:
      flutter: "3.24.0"
      java: "17"

    scripts:
      - flutter pub get

      # Create key.properties using Codemagic’s internal keystore variables
      - |
        cat > android/key.properties <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=$CM_KEY_ALIAS
        storeFile=$CM_KEYSTORE_PATH
        EOF

      # Build APK
      - flutter build apk --release

      # Build AAB
      - flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
