workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      vars:
        # Replace with your keystore info
        CM_KEYSTORE_PASSWORD: Encrypted
        CM_KEY_PASSWORD: Encrypted
        CM_KEY_ALIAS: Encrypted
      flutter: false
      xcode: false
      android:
        gradle_options: "--no-daemon"
    scripts:
      - name: Install dependencies
        script: ./gradlew clean
      - name: Assemble release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - you@example.com
