workflows:
  android-native-release:
    name: Android Native Release

    environment:
      java: "17"
      android: "latest"

    scripts:
      - chmod +x ./gradlew

      # Build APK
      - ./gradlew assembleRelease

      # Build AAB (if using bundle)
      - ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
