workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      vars:
        ANDROID_HOME: /Users/builder/Library/Android/sdk
        JAVA_HOME: /Applications/Android\ Studio.app/Contents/jbr/Contents/Home
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
